"""deleted worker in vacancy, changed ids to optional

Revision ID: 7153c0f348dc
Revises: 3690388d78fb
Create Date: 2025-08-18 15:14:21.148359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7153c0f348dc'
down_revision: Union[str, Sequence[str], None] = '3690388d78fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
